### ISSUE TITLE
How do you run?

### ISSUE THREAD

**Issue by ifeatu** [Michael-F-Bryan/noise-gate#1]
For the uninitiated to Rust...how do you run this project?  I tried going to the root of this project and doing a cargo build.  Doesn't generate a binary?!  Do you have to have a main in src/ ?

**Comment by Michael-F-Bryan** [comment]
The main crate is just a library (it's just a small building block in a project I'm working on), but you can use the `wav-splitter` example program to split a WAV file from the command-line.

For example the following command:

```console
$ cargo run --release --example wav-splitter -- --output-dir output --threshold 50 --release-time 0.3 data/N11379_KSCK.wav
$ ls output
clip_0.wav  clip_3.wav  clip_6.wav  clip_9.wav   clip_12.wav  clip_15.wav  clip_18.wav  clip_21.wav
clip_1.wav  clip_4.wav  clip_7.wav  clip_10.wav  clip_13.wav  clip_16.wav  clip_19.wav  clip_22.wav
clip_2.wav  clip_5.wav  clip_8.wav  clip_11.wav  clip_14.wav  clip_17.wav  clip_20.wav
```

Will run the `wav-splitter` example program against `data/N11379_KSCK.wav`, dumping the files to the `output/` directory.

**Comment by Michael-F-Bryan** [comment]
I've updated the README to include instructions on how to run the example and added more comments to the `wav-splitter` example. Let me know if there's anything else I can do to help!

**Comment by ifeatu** [comment]
Thanks!
