### ISSUE TITLE
Threshold Unit Isn't clear

### ISSUE THREAD

**Issue by Taha-Firoz** [Michael-F-Bryan/noise-gate#2]
I have this big set of audio data that I want to split up, the audio files have specific areas where the speech has been isolated with minimal sound near it but it isn't complete silence. I've attached an image of the waveform for reference. 
![image](https://user-images.githubusercontent.com/42237761/81505579-b93d1c00-9309-11ea-8f83-8b0644057a02.png)

I really can't get this project to cleanly split since I don't really understand how the threshold value works, like what it's unit is, and upon research, I can't find any reasonable unit. Pydub uses decibels to find silent areas in order to split audio. 

I tried experimenting with the values, while it does successfully split the file but it creates lots of junky files that range from a few bytes to 1-2 KBS. As a workaround, I've added a minimum length check to the code that circumvents the issue however when I run the code on all the files some aren't split properly. 
```rust
    fn end_of_transmission(&mut self, min_length: u32) {
        // if we were previously recording a transmission, remove the writer
        // and let it flush to disk
        if let Some(writer) = self.writer.take() {
            let duration = writer.duration(); 
            writer.finalize().unwrap();
            if duration < min_length{
                let filename = self
                .output_dir
                .join(format!("{}{}.wav", self.prefix, self.clip_number-1));
                fs::remove_file(filename).unwrap();
                self.clip_number -= 1;
            }
        }
    }
```

2 or words usually aren't split correctly in their silent sections, so technically it's still working properly since there's no loss of the actual words being said but since I need each word isolated in their own individual file it doesn't work for me.

These are the values of the arguments I had set to get a somewhat decent split, they're really far off from the values you've given in your examples.
```
--threshold 54     --release-time 0.0011 
```
Is there any way I can fix this, I thought maybe having a better threshold value or somehow alter the code to better split the files.

**Comment by Michael-F-Bryan** [comment]
The threshold should be in whatever units your sample is in (hence the `S: Sample` type parameter), and what value can be considered "good" will change depending on your input and taste. You can think of the noise gate as doing a literal `if next_sample < threshold { skip_it() }`, with a couple tweaks thrown in to implement the release time.

> I thought maybe having a better threshold value or somehow alter the code to better split the files.

One approach could be to change the threshold dynamically. So before/after you call `process_frames()` you could scan through the samples and use statistics to figure out what a "good" `threshold` is (e.g. `threshold = running_average - 3*std_dev` using something like [`streaming-stats`](https://docs.rs/streaming-stats/0.2.3/stats/)). 

I feel like updating it dynamically based on the input would be better than trying to find a threshold which works for all inputs ahead of time.

> I tried experimenting with the values, while it does successfully split the file but it creates lots of junky files that range from a few bytes to 1-2 KBS.

To help handle short bursts of unwanted sound we could also introduce some sort of `opening_time` which behaves similar to `release_time`, except at the start of a "word" (e.g. we need 20ms of sound above the threshold before it'll be passed through to the `Sink`)... Do you think that would work?

**Comment by Taha-Firoz** [comment]
> To help handle short bursts of unwanted sound we could also introduce some sort of opening_time which behaves similar to release_time, except at the start of a "word" (e.g. we need 20ms of sound above the threshold before it'll be passed through to the Sink)... Do you think that would work?

So would it be like that minimum size of I've added? Is there somehow I can share the changes in the code I've made without doing a PR, I've also added the ability to batch process files by just giving a folder.

> One approach could be to change the threshold dynamically. So before/after you call process_frames() you could scan through the samples and use statistics to figure out what a "good" threshold is (e.g. threshold = running_average - 3*std_dev using something like streaming-stats).

I guess that can give better results but I really think that'll only apply if the audio wasn't already isolated. If you look at the waveform I've provided each word is pretty well isolated from the other, if I could just somehow have the noise gate open only when there's a substantial increase in volume it would really help. When I run my file through your example values the noise gate doesn't detect a single split and just gives me the whole file.

**Comment by Michael-F-Bryan** [comment]
> When I run my file through your example values the noise gate doesn't detect a single split and just gives me the whole file.

Yeah, those values were specific to the clip I used [when creating the library](http://adventures.michaelfbryan.com/posts/audio-processing-for-dummies/). It needed a couple attempts to find a value that split things the way I liked.

> So would it be like that minimum size of I've added? Is there somehow I can share the changes in the code I've made without doing a PR

You could iterate locally, and if feasible, send me a link to the repo.

> I've also added the ability to batch process files by just giving a folder.

I probably wouldn't add this to the library. It's mainly intended as a primitive that people can use to build their own tools (like a batch processor) on top of.
